# Generated by Django 4.0.4 on 2023-03-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itm',
            new_name='item',
        ),
    ]
